services:
  app:
    container_name: sfta
    build: '.'
    ports:
      - '127.0.0.1:8080:80' # (Optional) Switch host port to avoid conflicts
    volumes:
      - '/var/www/sfta/uploads:/app/uploads:rw' # Match host volume with the web server config
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 80 # Internal container app port
      API_KEY: <openssl rand -hex 64>
      UPLOADS_DIR: /app/uploads # Internal container app directory
      FILE_SIZE_LIMIT: 1e+7 # 10MB
      WEB_UPLOADS_URL: http://localhost:8080/uploads # Match with the web server config
